[
    // All Canada Colleges
    "Cégep de Saint-Jérôme",
    "Ashton College",
    "British Columbia Institute of Technology",
    "Collège Boréal",
    "Brandon University",
    "Centennial College",
    "College of New Caledonia",
    "College of the Rockies",
    "University of Moncton, Shippagan",
    "University of Moncton, Edmundston",
    "Douglas College",
    "École nationale d'administration publique, Université du Québec",
    "École de technologie supérieure, Université du Québec",
    "École des Hautes Études Commerciales",
    "Institut Armand-Frappier, Université du Québec",
    "Institut National de la Recherche Scientifique, Université du Québec",
    "Kingston College",
    "Mount Saint Vincent University",
    "Mount Allison University",
    "Northern Alberta Institute of Technology",
    "Nipissing University",
    "Nova Scotia College of Art and Design",
    "Ontario College of Art and Design",
    "École Polytechnique de Montréal, Université de Montréal",
    "Queen's University",
    "Southern Alberta Institute of Technology",
    "Luther College",
    "Sheridan College",
    "St. Clair College",
    "St. Francis Xavier University",
    "St. Mary's University",
    "St. Thomas University",
    "Télé-université, Université du Québec",
    "Trent University",
    "University of the Fraser Valley",
    "Université Laval",
    "University of Lethbridge",
    "University of Moncton",
    "Université de Montréal",
    "University Canada West",
    "University of Guelph",
    "Université du Québec à Chicoutimi",
    "Université du Québec à Montréal",
    "Université du Québec à Rimouski",
    "Université du Québec en Abitibi-Témiscamingue",
    "Université du Québec en Outaouais",
    "Université du Québec à Trois-Rivières",
    "University of Regina",
    "Université de Sherbrooke",
    "St. Anne University",
    "St. Paul University",
    "University of Sudbury",
    "University of Victoria",
    "University of Waterloo",
    "Yukon College",
    "College of Bois-de-Boulogne",
    "Vanier College",
    "Collège Universel Gatineau",
    // USA universities & colleges 
    "Xavier University",
    "Chabot-Las Positas Community College District",
    "San Mateo County Community College District",
    "Los Rios Community College District",
    "College of Mount Saint Vincent",
    "University of Mary Washington",
    "Baldwin Wallace University",
    "California State University Channel Islands",
    "The Scripps Research Institute",
    "Western New England University",
    "Trident University",
    "Park University",
    "Riverside Community College District",
    "Wake Forest Baptist Health",
    "University of Findlay",
    "Philadelphia College of Osteopathic Medicine",
    "Yosemite Community College District",
    "Seattle Colleges",
    "Troy University",
    "42 US",
    "Maryville University",
    "University of Central Oklahoma",
    "St. Johns River State College",
    "Indian River State College",
    "University of La Verne",
    "University of the People",
    "Lesley University",
    "Pasco-Hernando State College",
    "New College of Florida",
    "Cold Spring Harbor Laboratory",
    "Contra Costa Community College District",
    "Mount St. Mary's University",
    "College of Southern Nevada",
    "The Principia",
    "Lynn University",
    "Valencia College",
    "Defense Language Institute Foreign Language Center",
    "Colorado State University - Global Campus",
    "North Dakota University System",
    "The College of New Jersey",
    "Agnes Scott College",
    "Alabama A&M University",
    "Alamo Colleges",
    "Alfred University",
    "Andrews University",
    "Antioch New England",
    "Aquinas College",
    "Barry University",
    "Bates College",
    "Bethany College",
    "Black Hills State University",
    "Boston College",
    "Boston University",
    "Bowling Green State University",
    "Bradley University",
    "Brandeis University",
    "California Institute of Technology",
    "California State University, Long Beach",
    "Calvin College",
    "Cameron University",
    "Campbellsville College",
    "Carroll College",
    "Carroll University",
    "Case Western Reserve University",
    "Cedarville College",
    "Centenary College of Louisiana",
    "Central College",
    "Central Michigan University",
    "Central Washington University",
    "Centre College",
    "Chatham College",
    "Chicago School of Professional Psychology",
    "Christian Theological Seminary",
    "Coastal Carolina University",
    "Coast Colleges",
    "Colby College",
    "College of Charleston",
    "College of Eastern Utah",
    "College of New Rochelle",
    "College of Saint Benedict",
    "College of Saint Catherine",
    "College of Saint Rose",
    "College of St. Francis",
    "College of St. Scholastica",
    "College of the Atlantic",
    "College of the Holy Cross",
    "College of William and Mary",
    "College of Wooster",
    "Colorado College",
    "Colorado School of Mines",
    "Connecticut College",
    "Allen College",
    "Daemen College",
    "Dana College",
    "Dartmouth College",
    "Dowling College",
    "Drew University",
    "East Carolina University",
    "Eastern Illinois University",
    "Eastern Kentucky University",
    "Eastern Michigan University",
    "Eastern New Mexico University",
    "Eastern Washington University",
    "Embry-Riddle Aeronautical University",
    "Emerson College",
    "Emmanuel College",
    "Lake Erie College of Osteopathic Medicine",
    "Fielding Institute",
    "Florida Gulf Coast University",
    "Florida Institute of Technology",
    "Fort Hays State University",
    "Franklin and Marshall College",
    "Franklin University",
    "Friends University",
    "Fuller Theological Seminary",
    "Geneva College",
    "George Mason University",
    "George Washington University",
    "Georgia College",
    "Georgia Institute of Technology",
    "Grace College",
    "Grand Valley State University",
    "Hampshire College",
    "Harding University",
    "Hastings College",
    "Hillsdale College",
    "Hobart and William Smith Colleges",
    "Hollins College",
    "Hope College",
    "Howard University",
    "Illinois Institute of Technology",
    "Indiana Institute of Technology",
    "Indiana University",
    "Indiana University - Bloomington",
    "Indiana University at South Bend",
    "Indiana University Southeast",
    "Institute for World Politics",
    "Iona College",
    "Jacksonville University",
    "James Madison University",
    "Johns Hopkins University Applied Physics Laboratory",
    "Kentucky Community & Technical College System",
    "Kettering University",
    "Lake Forest College",
    "Lake Superior College",
    "Lake Superior State University",
    "Lamar University",
    "La Sierra University",
    "Lawrence University",
    "Loma Linda University",
    "Loras College",
    "Los Angeles Community College District",
    "Louisiana College",
    "Luther College",
    "Luther Seminary",
    "Lycoming College",
    "Lyon College",
    "Manhattan College",
    "Marshall University",
    "Marymount Manhattan College",
    "Mary Washington College",
    "Massachusetts Institute of Technology",
    "Medical College of Georgia",
    "Medical College of Wisconsin",
    "Mercer County Community College",
    "Meredith College",
    "Metropolitan Community College (MO)",
    "Metropolitan Community College (NE)",
    "Denver College of Nursing",
    "Middlebury College",
    "Millsaps College",
    "Milwaukee School of Engineering",
    "Mississippi College",
    "Mississippi University for Women",
    "Missouri University of Science and Technology",
    "Monmouth College",
    "Monmouth University",
    "Montana Tech",
    "Mount Saint Joseph College",
    "Mount Saint Mary College",
    "National-Louis University",
    "National Radio Astronomy Observatory",
    "National University",
    "New College of California",
    "New England Institute of Technology",
    "New Hampshire College",
    "New Jersey Institute of Technology",
    "New York Institute of Technology",
    "New York University",
    "North Central Bible College",
    "Northeastern Louisiana University",
    "Northern Arizona University",
    "Northern Illinois University",
    "Northern Kentucky University",
    "Northern Michigan University",
    "Oakland University",
    "Occidental College",
    "Ohio University",
    "Oregon Institute of Technology",
    "Our Lady of the Lake University",
    "Pacific University",
    "Palm Beach Atlantic College",
    "Palm Beach State College",
    "Peace College",
    "Pennsylvania College of Technology",
    "Pennsylvania State University - Schuylkill Campus",
    "Philadelphia University",
    "Prairie View A&M University",
    "Purdue University North Central",
    "Quincy University",
    "Regis University",
    "Rhode Island College",
    "Rhodes College",
    "Rice University",
    "Rivier College",
    "Rollins College",
    "Rowan College",
    "Rutgers University",
    "Sage Colleges",
    "Saginaw Valley State University",
    "Saint Cloud State University",
    "Saint Edward's University",
    "St. Francis College",
    "Saint John's University (NY)",
    "Saint Joseph's College (IN)",
    "Saint Joseph's University",
    "Saint Louis University",
    "Saint Mary College",
    "Saint Mary's College (IN)",
    "Saint Mary's College of California",
    "Saint Michael's College",
    "Saint Vincent College",
    "Saint Xavier University",
    "Salisbury University",
    "Santa Clara University",
    "Sarah Lawrence College",
    "Seattle University",
    "Sewanee, University of the South",
    "Shorter College",
    "South Dakota School of Mines and Technology",
    "Southeastern Louisiana University",
    "Southern College",
    "Southern College of Technology",
    "Southern Illinois University-Carbondale",
    "Southern Illinois University-Edwardsville",
    "Southern New Hampshire University",
    "Southern University and A&M College",
    "Southern Utah University",
    "South Texas College of Law",
    "St. Andrews Presbyterian College",
    "Stephens College",
    "St. John's College - Annapolis",
    "St. John's College - Santa Fe",
    "St. Joseph College (CT)",
    "St. Joseph's College (ME)",
    "St. Lawrence University",
    "St. Louis College of Pharmacy",
    "St. Martin's College",
    "St. Mary's College of Maryland",
    "St. Thomas University (FL)",
    "Suffolk University",
    "Texas A&M University - College Station",
    "Texas A&M University - Commerce",
    "Texas A&M University - Corpus Christi",
    "Texas A&M University - Kingsville",
    "Texas Tech University-Health Sciences Center",
    "The Citadel",
    "The Jewish Theological Seminary",
    "Thomas College",
    "Tufts University",
    "University of Advancing Technology",
    "University of Akron",
    "University of Baltimore",
    "University of Bridgeport",
    "University of Central Arkansas",
    "University of Central Florida",
    "University of Central Missouri",
    "University of Charleston",
    "University of Cincinnati",
    "University of Dayton",
    "University of Dubuque",
    "University of Evansville",
    "University of Great Falls",
    "University of Hartford",
    "University of Houston",
    "University of Jamestown",
    "University of Louisville",
    "University of New Haven",
    "University of Puget Sound",
    "University of Redlands",
    "University of Richmond",
    "University of Rochester",
    "University of Saint Thomas (MN)",
    "University of Saint Thomas (TX)",
    "University of Scranton",
    "University of Sioux Falls",
    "University of Southwestern Louisiana",
    "University of Tampa",
    "University of the District of Columbia",
    "University of the Incarnate Word",
    "University of the Ozarks",
    "University of the Pacific",
    "University of Toledo",
    "Upper Iowa University",
    "Valley City State University",
    "Villa Julie College",
    "Virginia Tech",
    "Washington Bible College/Capital Bible Seminary",
    "Washington College",
    "Washington University, Saint Louis",
    "Wells College",
    "Wesley College",
    "Western Carolina University",
    "Western Illinois University",
    "Western Kentucky University",
    "Western Michigan University",
    "Western Montana College",
    "Western New England College",
    "Western New Mexico University",
    "Western State Colorado University",
    "Western Washington University",
    "West Georgia College",
    "West Liberty State College",
    "Westminster Theological Seminary",
    "West Texas A&M University",
    "West Virginia University",
    "West Virginia University at Parkersburg",
    "Whittier College",
    "Wilkes University",
    "William Mitchell College of Law",
    "William Penn College",
    "Woodbury University",
    "Brookings Institution",
    "Bevill State Community College",
    "Bishop State Community College",
    "Chattahoochee Valley Community College",
    "Enterprise State Community College",
    "Gadsden State Community College",
    "George C Wallace State Community College-​Dothan",
    "George C Wallace State Community College-​Hanceville",
    "George C Wallace State Community College-​Selma",
    "H Councill Trenholm State Technical College",
    "James H Faulkner State Community College",
    "Lurleen B Wallace Community College",
    "Snead State Community College",
    "Southern Union State Community College",
    "Central Arizona College",
    "Cochise College",
    "Eastern Arizona College",
    "Paradise Valley Community College",
    "Phoenix College",
    "South Mountain Community College",
    "Tohono O'Odham Community College",
    "Arkansas State University-​Beebe",
    "Arkansas State University-​Mountain Home",
    "Arkansas State University-​Newport",
    "Black River Technical College",
    "College of the Ouachitas",
    "National Park Community College",
    "North Arkansas College",
    "Rich Mountain Community College",
    "Southeast Arkansas College",
    "Southern Arkansas University Tech",
    "American River College",
    "Bakersfield College",
    "Canada College",
    "Cerritos College",
    "Cerro Coso Community College",
    "College of Alameda",
    "College of Marin",
    "College of San Mateo",
    "College of the Canyons",
    "College of the Desert",
    "College of the Redwoods",
    "College of the Sequoias",
    "College of the Siskiyous",
    "Copper Mountain Community College",
    "Cosumnes River College",
    "East Los Angeles College",
    "El Camino College-​Compton Center",
    "El Camino Community College District",
    "Feather River Community College District",
    "Folsom Lake College",
    "Lake Tahoe Community College",
    "Los Angeles Pierce College",
    "Mt. San Antonio College",
    "Mt. San Jacinto Community College District",
    "Porterville College",
    "San Bernardino Valley College",
    "San Joaquin Valley College-​Visalia",
    "Santa Ana College",
    "Santa Monica College",
    "Sierra College",
    "West Hills College-​Coalinga",
    "West Los Angeles College",
    "Front Range Community College",
    "Pikes Peak Community College",
    "Red Rocks Community College",
    "Trinidad State Junior College",
    "Naugatuck Valley Community College",
    "Quinebaug Valley Community College",
    "Three Rivers Community College",
    "Delaware College of Art and Design",
    "Andrew College",
    "Coastal Pines Technical College",
    "Southern Crescent Technical College",
    "College of Southern Idaho",
    "College of Western Idaho",
    "North Idaho College",
    "City Colleges of Chicago",
    "College of DuPage",
    "College of DuPage",
    "College of Lake County",
    "Danville Area Community College",
    "John A Logan College",
    "Lake Land College",
    "Moraine Valley Community College",
    "Northwestern College-​Chicago Campus",
    "Rend Lake College",
    "Sauk Valley Community College",
    "Southeastern Illinois College",
    "Southwestern Illinois College",
    "Spoon River College",
    "Ivy Tech Community College",
    "Des Moines Area Community College",
    "Eastern Iowa Community College District",
    "North Iowa Area Community College",
    "Western Iowa Tech Community College",
    "Barton County Community College",
    "Cloud County Community College",
    "Cowley County Community College",
    "Dodge City Community College",
    "Flint Hills Technical College",
    "Garden City Community College",
    "Neosho County Community College",
    "North Central Kansas Technical College",
    "Galen College of Nursing-​Louisville",
    "Baton Rouge Community College",
    "Bossier Parish Community College",
    "L E Fletcher Technical Community College",
    "Louisiana State University-​Eunice",
    "River Parishes Community College",
    "Southern University at Shreveport",
    "SOWELA Technical Community College",
    "Kennebec Valley Community College",
    "York County Community College",
    "Baltimore City Community College",
    "Cecil College",
    "College of Southern Maryland",
    "Garrett College",
    "Bunker Hill Community College",
    "Cape Cod Community College",
    "Mount Wachusett Community College",
    "North Shore Community College",
    "Quincy College",
    "Springfield Technical Community College",
    "Urban College of Boston",
    "Bay Mills Community College",
    "Grand Rapids Community College",
    "Kalamazoo Valley Community College",
    "Keweenaw Bay Ojibwa Community College",
    "Lake Michigan College",
    "North Central Michigan College",
    "Saginaw Chippewa Tribal College",
    "Southwestern Michigan College",
    "St. Clair County Community College",
    "Wayne County Community College District",
    "West Shore Community College",
    "Alexandria Technical & Community College",
    "Central Lakes College-​Brainerd",
    "Dakota County Technical College",
    "Inver Hills Community College",
    "Leech Lake Tribal College",
    "Minnesota State College-​Southeast Technical",
    "North Hennepin Community College",
    "Rainy River Community College",
    "Saint Paul College",
    "East Central Community College",
    "Mississippi Gulf Coast Community College",
    "Pearl River Community College",
    "Linn State Technical College",
    "Missouri State University-​West Plains",
    "Moberly Area Community College",
    "North Central Missouri College",
    "Ozarks Technical Community College",
    "State Fair Community College",
    "Three Rivers Community College",
    "Wentworth Military Academy & Junior College",
    "Chief Dull Knife College",
    "Flathead Valley Community College",
    "Fort Peck Community College",
    "Great Falls College Montana State University",
    "Little Big Horn College",
    "Little Priest Tribal College",
    "Nebraska College of Technical Agriculture",
    "Southeast Community College Area",
    "Truckee Meadows Community College",
    "Great Bay Community College",
    "Lakes Region Community College",
    "River Valley Community College",
    "White Mountains Community College",
    "Atlantic Cape Community College",
    "Hudson County Community College",
    "Passaic County Community College",
    "Raritan Valley Community College",
    "Eastern New Mexico University-​Roswell Campus",
    "New Mexico State University-​Alamogordo",
    "New Mexico State University-​Carlsbad",
    "New Mexico State University-​Dona Ana",
    "San Juan College",
    "Cayuga County Community College",
    "CUNY Bronx Community College",
    "CUNY Hostos Community College",
    "CUNY Kingsborough Community College",
    "CUNY LaGuardia Community College",
    "CUNY Queensborough Community College",
    "CUNY City Tech",
    "CUNY Brooklyn College",
    "CUNY Medgar Evers College",
    "CUNY Macauly Honors College",
    "Finger Lakes Community College",
    "Herkimer County Community College",
    "Hudson Valley Community College",
    "Mohawk Valley Community College",
    "Niagara County Community College",
    "North Country Community College",
    "Saint Elizabeth College of Nursing",
    "Schenectady County Community College",
    "SUNY Broome Community College",
    "SUNY Westchester Community College",
    "Tompkins Cortland Community College",
    "Ulster County Community College",
    "Asheville-​Buncombe Technical Community College",
    "Beaufort County Community College",
    "Blue Ridge Community College",
    "Cape Fear Community College",
    "Carolinas College of Health Sciences",
    "Catawba Valley Community College",
    "Central Piedmont Community College",
    "College of the Albemarle",
    "Davidson County Community College",
    "Durham Technical Community College",
    "Fayetteville Technical Community College",
    "Forsyth Technical Community College",
    "Guilford Technical Community College",
    "McDowell Technical Community College",
    "South Piedmont Community College",
    "Wake Technical Community College",
    "Western Piedmont Community College",
    "Cankdeska Cikana Community College",
    "Lake Region State College",
    "Columbus State Community College",
    "Cuyahoga Community College District",
    "Eastern Gateway Community College",
    "Hocking College",
    "James A Rhodes State College",
    "Lorain County Community College",
    "North Central State College",
    "Northwest State Community College",
    "Ohio State University Agricultural Technical Institute",
    "Southern State Community College",
    "Terra State Community College",
    "University of Akron Wayne College",
    "Northeastern Oklahoma A&M College",
    "Northern Oklahoma College",
    "Blue Mountain Community College",
    "Columbia Gorge Community College",
    "Mt. Hood Community College",
    "Tillamook Bay Community College",
    "Treasure Valley Community College",
    "Bucks County Community College",
    "Butler County Community College",
    "Harrisburg Area Community College-​Harrisburg",
    "Lehigh Carbon Community College",
    "Luzerne County Community College",
    "Montgomery County Community College",
    "Pennsylvania Institute of Technology",
    "Reading Area Community College",
    "University of Pittsburgh-​Titusville",
    "Westmoreland County Community College",
    "Orangeburg Calhoun Technical College",
    "Technical College of the Lowcountry",
    "Lake Area Technical Institute",
    "Western Dakota Technical Institute",
    "Chattanooga State Community College",
    "Columbia State Community College",
    "Dyersburg State Community College",
    "Motlow State Community College",
    "Northeast State Community College",
    "Pellissippi State Community College",
    "Roane State Community College",
    "Volunteer State Community College",
    "Walters State Community College",
    "Angelina College",
    "Brookhaven College",
    "Central Texas College",
    "College of the Mainland",
    "Collin County Community College District",
    "Howard College",
    "Jacksonville College-​Main Campus",
    "Lamar Institute of Technology",
    "Lamar State College-​Orange",
    "Lamar State College-​Port Arthur",
    "Lone Star College System",
    "North Central Texas College",
    "North Lake College",
    "Odessa College",
    "Alamo Colleges District",
    "Texas State Technical College-​Harlingen",
    "Texas State Technical College-​Marshall",
    "Texas State Technical College-​Waco",
    "Texas State Technical College-​West Texas",
    "Trinity Valley Community College",
    "Vernon College",
    "Western Texas College",
    "Wharton County Junior College",
    "Salt Lake Community College",
    "Blue Ridge Community College",
    "Dabney S Lancaster Community College",
    "Eastern Shore Community College",
    "J Sargeant Reynolds Community College",
    "Lord Fairfax Community College",
    "Mountain Empire Community College",
    "New River Community College",
    "Paul D Camp Community College",
    "Big Bend Community College",
    "Clover Park Technical College",
    "Green River Community College",
    "Pierce College at Puyallup",
    "South Puget Sound Community College",
    "Spokane Falls Community College",
    "Walla Walla Community College",
    "Yakima Valley Community College",
    "Chippewa Valley Technical College",
    "Fox Valley Technical College",
    "Lac Courte Oreilles Ojibwa Community College",
    "Moraine Park Technical College",
    "Nicolet Area Technical College",
    "Waukesha County Technical College",
    "Central Wyoming College",
    "Eastern Wyoming College",
    "Laramie County Community College",
    "Northwest College",
    "Sheridan College",
    "Savannah College of Art and Design",
    "Gulf Coast State College",
    "Clark Atlanta University",
    "Morehouse",
    "California Institute of the Arts",
    "Maryville College",
    "Einsteinmed",
    "Bishop McNamara High School",
    "Ojai Unified School District",
    "Allen University",
    "Arkansas at Pine Bluff, University of",
    "Fort Valley State University",
    "Gasden State Community College",
    "Hood Theological",
    "Johnson C Smith Theological Seminary *",
    "Knoxville College",
    "Lawson State Community College",
    "LeMoyne-Owen College",
    "Miles College",
    "Miles School of Law",
    "Paul Quinn College",
    "Rust College",
    "Selma University",
    "Southern University at New Orleans",
    "Texas College",
    "Virginia University of Lynchburg",
    "Voorhees University",
    "Wiley College",
    "Texas A&M University-Texarkana",
    "Belhaven University"
]
